apiVersion: apps/v1
kind: Deployment
metadata:
  name: passin-deployment
  labels:
    app: passin
spec:
  selector:
    matchLabels:
      app: passin
  replicas: 5
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
        - name: passin
          image: adadriano/nlw.service.passin:ece8dd2
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: url
            - name: API_BASE_URL
              value: "http://localhost:3333"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3333
