apiVersion: apps/v1
kind: Deployment
metadata:
  name: passin-deployment
  labels:
    app: passin
spec:
  selector:
    matchLabels:
      app: passin
  replicas: 5
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: nginx:1.25.4-alpine3.18-slim
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 80